### PR TITLE
Mllib 1.5 tests

### PR DESCRIPTION
**Pull request by feynmanliang**
* Copy/paste of `mllib-tests/v1p4` -> `mllib-tests/v1p5`; no changes otherwise
 * Add `./c` (generated while running perf tests) to `.gitignore`

### CODE REVIEW

**Comment by feynmanliang** [comment]
@jkbradley Do you mind reviewing and merging this? It blocks #80

**Comment by jkbradley** [comment]
Did you compile this for 1.5 already?  If that worked, then I'll merge this without careful checking, after fixing merge conflicts.

**Comment by feynmanliang** [comment]
Yep, this works but since 1.5 isn't an official release yet you will need to:
 * Set `USE_CLUSTER_SPARK = True` and `MLLIB_SPARK_VERSION = 1.5` in `config.py`
 * Don't use `PREP_MLLIB_TESTS = True`; instead manually run `cd mllib-tests; sbt/sbt -Dspark.version=1.5.0-SNAPSHOT clean assembly` to build the mllib perf tests

These steps are necessary because we are building against snapshot. This should be fixed once we can build against an official 1.5 release.

**Comment by jkbradley** [comment]
I'll merge this, but in the next PR, can you please add those comments in doc somewhere?  Thanks!

**Pull request merged**
