### PR TITLE
use container-based infra for travis

### PR DESCRIPTION
**Pull request by mengxr**
http://docs.travis-ci.com/user/workers/container-based-infrastructure/

### CODE REVIEW

**Comment by mengxr** [comment]
@JoshRosen We need sudo to install `nose`. What is it used for?

**Comment by JoshRosen** [comment]
@mengxr We use the `nose` test runner to run Python tests for the `sparkperf` library:

https://github.com/databricks/spark-perf/blob/master/run-tests.sh

We probably don't need to use `sudo` for this, though; I wrote this configuration file before the container-based infrastructure existed.

**Comment by JoshRosen** [comment]
Can you try just removing the `sudo` and installing `nose` with regular permissions?

**Comment by mengxr** [comment]
From http://docs.travis-ci.com/user/build-configuration/#Installing-Packages-Using-apt:

> Note that this feature is not available for builds that are running on the container-based workers.

**Comment by JoshRosen** [comment]
Doesn't that only apply to things installed via `apt-get` though?  It's not obvious that it applies to `pip`.

**Comment by mengxr** [comment]
I thought that was installed via `apt-get`. Let's try a local dir for nose.

**Comment by mengxr** [comment]
@JoshRosen With the current setup, each build runs in 3.5 mins, compared to 6~7 mins before. This is more stable on fetching jars from maven central repos.

**Comment by JoshRosen** [comment]
@mengxr Sounds good to me; feel free to merge.

**Pull request closed without merging**
