### PR TITLE
Remove support in mllib-perf for Spark 1.0, 1.1, 1.2, and 1.3

### PR DESCRIPTION
**Pull request by mengxr**
This PR removes mllib-perf sub-projects for 1.0-1.3 and updates the build file. @jkbradley

### CODE REVIEW

**Comment by jkbradley** [comment]
LGTM  I'll merge this and then update my PR

**Comment by nchammas** [comment]
Should we also update the README? It [currently reads](https://github.com/databricks/spark-perf/blob/93e456047a9eca4fb7bf3119ab80d293e25f360b/README.md#spark-performance-tests):

> This is a performance testing framework for Apache Spark 1.0+.

**Comment by jkbradley** [comment]
Maybe, but do the Core or other tests still work for earlier versions?

**Comment by nchammas** [comment]
I haven't tried them recently, but I would assume they do. If Core is the focus of spark-perf, then perhaps the README should remain as-is.

**Pull request merged**
