### PR TITLE
Mention that you need to build the tests in the README

### PR DESCRIPTION
**Pull request by holdenk**

### CODE REVIEW

**Comment by JoshRosen** [comment]
AFAIK the test framework itself is supposed to take care of this automatically:

https://github.com/databricks/spark-perf/blob/9bc5ecd8aea1b718ede75865968672c6c0aa0a00/lib/sparkperf/testsuites.py#L142

**Comment by holdenk** [comment]
hmmm. I wonder why that wasn't triggered for me. I'll close this then :)

**Comment by JoshRosen** [comment]
Ah, I think I know why:

in config.py:

```python
# Which tests to prepare. Set this to true for the first
# installation or whenever you make a change to the tests.
PREP_SPARK_TESTS = True
PREP_PYSPARK_TESTS = False
PREP_STREAMING_TESTS = False
PREP_MLLIB_TESTS = False

```

**Comment by JoshRosen** [comment]
Actually, maybe we should either better document these confs or just remove them and recompile each time, since it seems confusing.

**Comment by holdenk** [comment]
Or just switch the default to true (or improve error message to say please set it config.py)?

**Comment by JoshRosen** [comment]
@holdenk Any or all of those suggestions sound good; I'm too busy to make those changes myself right now, but feel free to re-open and add those fixes.

**Comment by holdenk** [comment]
Cool, I'll do one of these tonight :)

**Pull request closed without merging**
