### PR TITLE
Fix Hadoop version at 1.2.1 when making a Spark distribution

### PR DESCRIPTION
**Pull request by nchammas**
The default version of Hadoop that Spark builds against changed around a month or two ago. This PR fixes the version of Hadoop at was it was before that change.

We will probably want to put this somewhere else eventually, maybe make it an option as part of some refactoring in #64.

### CODE REVIEW

**Comment by nchammas** [comment]
Hmm, actually the [latest docs](https://github.com/apache/spark/blob/master/docs/building-spark.md#apache-hadoop-121) say we should use this to build against Hadoop 1:

```
-Dhadoop.version=1.2.1 -Phadoop-1
```

So now I'm confused about what the right thing to do is. Perhaps the "right thing" has changed with Spark versions, which is fine.

I guess it's not surprising that it's hard (or maybe impossible) to have one magic build configuration that works for old and new versions of Spark alike.

**Comment by nchammas** [comment]
cc @pwendell - You may have some thoughts on this.

**Comment by JoshRosen** [comment]
This issue just bit me while running some Spark 1.5.0 tests. When running tests on Spark-EC2 which require HDFS, I think the easiest approach is to just use the `hadoop-provided` profile to build Spark. However, this configuration will probably be annoying to users who want to run `spark-perf` on their own cluster which does not have any version of HDFS installed. As a result, I think the right approach is to make this configurable via `configuration.py` and to provide some documentation / examples of how to configure things for different scenarios. I'm going to put together a pull request for this shortly.

**Comment by nchammas** [comment]
@JoshRosen - I believe I did make the Hadoop version configurable in #76, but you may want to change the approach taken there.

**Pull request closed without merging**
